### ISSUE TITLE
[New Project]: Make GitHub Issues endless on web

### ISSUE THREAD

**Issue by skanda890** [github/forgoodfirstissue#104]
### Does this project already exist in the app?

- [X] I have searched the existing projects

No, this project doesn't exist in the app.

### Tell us about the project

Rather than scrolling pages, make Github endless, on the web.

### Is the Project a DPG (Digital Public Good)

- [ ] Yes
- [X] No

### Does the project list which Sustainable Development Goals it addresses in its labels?

- [ ] Yes
- [ ] No

### Code of Conduct

- [X] I've read the Code of Conduct and understand my responsibilities as a member of the GitHub community

**Comment by seanmarcia** [comment]
This GitHub repository is for the the website: forgoodfirstissue.github.com so your issue does not make sense.

**Comment by skanda890** [comment]
Okay
