### ISSUE TITLE
[New Project]: Back In Time

### ISSUE THREAD

**Issue by buhtz** [github/forgoodfirstissue#113]
### Is this project already existing in the app?

- [X] I have searched the existing projects

### Tell us about the project

Back In Time is an an an easy-to-use backup tool for GNU Linux using rsync in the back.
The current maintenance team consists of three active members (3rd generation of maintainers in that project) plus the former maintainer. All working voluntarily in their spare time.
The project itself is round about 15 years old, written in Python using PyQt as a GUI. Its features depend on rsync.

### Is the Project a DPG (Digital Public Good)

- [ ] Yes
- [X] No

### Does the project list which Sustainable Development Goals it addresses in its labels?

- [ ] Yes
- [ ] No

### Code of Conduct

- [X] I've read the Code of Conduct and understand my responsibilities as a member of the GitHub community

### Anything else?

I am part of the current maintenance team.

**Comment by seanmarcia** [comment]
Do you have a link to the repo to check this out?

**Comment by buhtz** [comment]
Sorry. 😆 
https://github.com/bit-team/backintime

**Comment by seanmarcia** [comment]
Awesome, looks like a  great project and we'd be happy to add it! Just one request, would you mind adding a code of conduct?

**Comment by buhtz** [comment]
We are a team and currently I can not speak for the project but just for me.
I never understood the reaons for a coc. Prove me wrong. I am willing to learn.

We are humans. We have laws.
People who don't want to be polite and ignoring the law will always ignore a coc.

I don't understand how a coc can help with improving a project.

**Comment by seanmarcia** [comment]
I completely understand that bad actors will ignore a CoC. It does signal that the maintainers care about contributors and do not tolerate abusive or unkind behaviour.

https://docs.github.com/en/communities/setting-up-your-project-for-healthy-contributions/adding-a-code-of-conduct-to-your-project

**Comment by buhtz** [comment]
Not having a CoC do signal that we don't care?

**Comment by seanmarcia** [comment]
**Having** a CoC is a signal that you do care about how your contributors are treated. Not having a CoC doesn't signal anything good or bad.

**Comment by buhtz** [comment]
> Not having a CoC doesn't signal anything good or bad.
Nice to know. Because I see no need to "send such a signal" because it is implicit and obvious that I do care about contributors. I do think of the best of all human beings until they proof me the opposite.

**Comment by seanmarcia** [comment]
Got it and I understand. Let me know if you decide to add a code of conduct and we'll get your project added!
