### ISSUE TITLE
Featured project maintainer here: It says 0 issues but we see 13. What label do you want us to use? 

### ISSUE THREAD

**Issue by SallyMcGrath** [github/forgoodfirstissue#116]
**Is your feature request related to a problem? Please describe.**
Hi I maintain https://github.com/CodeYourFuture/curriculum and https://github.com/CodeYourFuture/immersive-go-course which are both DPGs.

Thanks so much for featuring us. ❤️ 

As requested, we [labelled a bunch of approachable issues](https://github.com/CodeYourFuture/curriculum/issues?q=is%3Aissue+is%3Aopen+label%3Asdg-4) with `sdg-4`  

But on your site it says 0 issues
https://forgoodfirstissue.github.com/

<img width="1510" alt="Screenshot 2024-01-26 at 16 38 21" src="https://github.com/github/forgoodfirstissue/assets/42203406/f3781e6e-3ae5-4e08-9907-47605127073e">

**Describe the solution you'd like**
I'd like the issues we labelled with sdg-4 to show up on the website.

Or another label you prefer - we don't mind what we call the label! :) Just let us know if we've misunderstood the label name and need to update it. 🙏 

**Describe alternatives you've considered**

We also tried `SDG-4` just in case...

**Additional context**

Thanks again for all your hard work!

**Comment by seanmarcia** [comment]
It looks for the labels `help wanted` and `good first issue` :)

**Comment by SallyMcGrath** [comment]
All better thank you! ❤️
