### ISSUE TITLE
[New Project]: DHIS2 UI Library

### ISSUE THREAD

**Issue by kabaros** [github/forgoodfirstissue#117]
### Is this project already existing in the app?

- [X] I have searched the existing projects

### Tell us about the project

https://github.com/dhis2/ui

DHIS2 is the world's largest open-source health information management system. Another project from the organisation is already listed (dhis2-core), but not this one. This is the UI library used for building  DHIS2 applications and we want to start exposing some of the issues we want to tackle there for help from the global community.

### Is the Project a DPG (Digital Public Good)

- [X] Yes
- [ ] No

### Does the project list which Sustainable Development Goals it addresses in its labels?

- [X] Yes
- [ ] No

### Code of Conduct

- [X] I've read the Code of Conduct and understand my responsibilities as a member of the GitHub community

### Anything else?

The project _is_ a DPG, but I can't submit the form unless I choose No as an answer

**Comment by seanmarcia** [comment]
Added via your PR! :)
