### ISSUE TITLE
[New Project]: Chamilo LMS

### ISSUE THREAD

**Issue by ywarnier** [github/forgoodfirstissue#130]
### Is this project already existing in the app?

- [X] I have searched the existing projects

### Tell us about the project

Chamilo is an Open Source Learning Management System that vows to help increase the availability of quality education around the world. Its main "technical" focus is to be easy to use, as we believe this solves the most complicated part of providing education through a computer system. Chamilo exists since 2010 and has already been used by more than 30 million users in more than 180 countries.

### Is the Project a DPG (Digital Public Good)

- [ ] Yes
- [X] No

### Does the project list which Sustainable Development Goals it addresses in its labels?

- [ ] Yes
- [X] No

### Code of Conduct

- [X] I've read the Code of Conduct and understand my responsibilities as a member of the GitHub community

**Comment by seanmarcia** [comment]
Can you provide link to the project?

**Comment by seanmarcia** [comment]
Ping @ywarnier

**Comment by ywarnier** [comment]
Sure, sorry didn't see your 1st message.
Repo : https://github.com/chamilo/chamilo-lms
Project website : https://chamilo.org
Demo portal : https://campus.chamilo.org

**Comment by seanmarcia** [comment]
@ywarnier this is awesome! We'll get it added shortly :)

As a FYI, the FGFI application displays issues that are labeled "Help Wanted" or "Good First Issue" :)

Keep up the amazing work.

**Comment by ywarnier** [comment]
Great, thanks! As an additional info, we have recently been approved as a Digital Public Good in education. This was after submitting the form with you.

**Comment by seanmarcia** [comment]
Fantastic! I look forward to chatting with you on an upcoming DPG member call! Or seeing you at an event sometime :)
