### ISSUE TITLE
Online Parking Reservation Website

### ISSUE THREAD

**Issue by HeyFang** [github/forgoodfirstissue#145]
### Is this project already existing in the app?

- [X] I have searched the existing projects

### Tell us about the project

repo: https://github.com/HeyFang/parkez

It is a basic website created with HTML, CSS and JS for front end and PHP & MYSQL for backend.
it would be ideal starting point for webdev beginners, and cool project to work on.

### Is the Project a DPG (Digital Public Good)

- [ ] Yes
- [X] No

### Does the project list which Sustainable Development Goals it addresses in its labels?

- [X] Yes
- [ ] No

### Code of Conduct

- [X] I've read the Code of Conduct and understand my responsibilities as a member of the GitHub community

**Comment by seanmarcia** [comment]
Hey @HeyFang, this looks like a fun project! For good first issue is for active projects that are helping nonprofits and other social sector organizations.
