### ISSUE TITLE
Website uses project-name/org-name instead of org-name/project-name

### ISSUE THREAD

**Issue by DanielRosenwasser** [github/forgoodfirstissue#80]
Usually everything on GitHub uses the format org-name/project-name.

Is it intentional that the website (https://forgoodfirstissue.github.com/) has these reversed? 

![image](https://github.com/github/forgoodfirstissue/assets/972891/0fecfbd6-42ef-4afa-8c50-74d270c2b870)

**Comment by JamesMGreene** [comment]
Came to report this as well. 😅 

Looks like that is rendered from here (and yes, they are indeed backwards):

https://github.com/github/forgoodfirstissue/blob/732d8f2409db04f2416ad0447ac82c4ffd6dce89/components/RepositoryItemTopBar.tsx#L28-L35

**Comment by JamesMGreene** [comment]
Offered up a PR:
- https://github.com/github/forgoodfirstissue/pull/83
