### ISSUE TITLE
[New Project]: Drupal

### ISSUE THREAD

**Issue by laurielim** [github/forgoodfirstissue#85]
### Is this project already existing in the app?

- [X] I have searched the existing projects

### Tell us about the project

Drupal is an open source content management system that is a Digital Public Good (Ref: https://app.digitalpublicgoods.net/a/10499). This is their gh repo https://github.com/drupal/drupal but it is just a public mirror, they have their own [GitLab repository](https://git.drupalcode.org/project/drupal) and [issue queue](https://www.drupal.org/project/issues/drupal). The list of DPG for PHP is quite slim so I think this would be a good addition. The issue queue has a [Novice tag](https://www.drupal.org/project/issues/search/drupal?issue_tags=Novice) .

### Is the Project a DPG (Digital Public Good)

- [X] This Project is a DPG

### Does the project list which Sustainable Development Goals it addresses in its labels?

- [X] Yes
- [ ] No

### Code of Conduct

- [X] I've read the Code of Conduct and understand my responsibilities as a member of the Ruby for Good community

**Comment by seanmarcia** [comment]
Drupal has been added :)
