### ISSUE TITLE
[New Project]: CircuLaw

### ISSUE THREAD

**Issue by gurdenbatra** [github/forgoodfirstissue#86]
### Is this project already existing in the app?

- [X] I have searched the existing projects

### Tell us about the project

CircuLaw is a knowledge platform dedicated to enabling the transition to a circular economy by identifying opportunities in current law to support a circular future. Amidst the escalating climate crisis, the global community is under significant pressure to transition towards a more sustainable and circular economy. With the European Union’s Circular Economy Action Plan and the Dutch government's commitment to a 50% reduction in the use of primary raw materials by 2030, formal commitment to this transition is taking shape. CircuLaw identifies opportunities in current law to support this circular future.

The open source repo can be found [here](https://github.com/Dark-Matter-Labs/circulaw) and deployed app [here](https://www.circulaw.nl/).

It is built using NextJS and Sanity.

### Is the Project a DPG (Digital Public Good)

- [X] This Project is a DPG

### Does the project list which Sustainable Development Goals it addresses in its labels?

- [ ] Yes
- [X] No

### Code of Conduct

- [X] I've read the Code of Conduct and understand my responsibilities as a member of the Ruby for Good community

**Comment by seanmarcia** [comment]
Hey Gurden! This looks like a great project and we'd love to add it. Would you mind adding a code of conduct to your project?

**Comment by seanmarcia** [comment]
Hey @gurdenbatra I'm going to close this issue. Definitely let us know if you've added a code of conduct and re-open it later when you have!
