### ISSUE TITLE
[New Project]: SORMAS - Surveillance Outbreak Response Management and Analysis System

### ISSUE THREAD

**Issue by SORMAS-JanBoehme** [github/forgoodfirstissue#87]
### Is this project already existing in the app?

- [X] I have searched the existing projects

### Tell us about the project

SORMAS is an open source mobile and web-based eHealth software for organizing and facilitating disease control, outbreak management procedures, disease surveillance, and epidemiological analysis for all administrative levels of the public health system. SORMAS aims to improve prevention, early detection and control of communicable diseases. SORMAS adheres to the highest data protection standards, good scientific practice, and open access policy.

### Is the Project a DPG (Digital Public Good)

- [X] This Project is a DPG

### Does the project list which Sustainable Development Goals it addresses in its labels?

- [X] Yes
- [ ] No

### Code of Conduct

- [X] I've read the Code of Conduct and understand my responsibilities as a member of the Ruby for Good community

### Anything else?

website: https://www.sormas.org
github: https://github.sorm.as
community platform: https://community.sorm.as

**Comment by seanmarcia** [comment]
Updated the link.
