### ISSUE TITLE
[Update Project]: Surveillance Outbreak Response Management and Analysis System (SORMAS)

### ISSUE THREAD

**Issue by Candice-Louw** [github/forgoodfirstissue#88]
### Is this project already existing in the app?

- [X] I have searched the existing projects

### Tell us about the project

Old, existing project link (currently in happycommits.json):
https://github.com/hzi-braunschweig/SORMAS-Project

New project link (to replace link above, please):
https://github.com/SORMAS-Foundation/SORMAS-Project

### Is the Project a DPG (Digital Public Good)

- [X] This Project is a DPG

### Does the project list which Sustainable Development Goals it addresses in its labels?

- [ ] Yes
- [x] No

### Code of Conduct

- [X] I've read the Code of Conduct and understand my responsibilities as a member of the Ruby for Good community

### Anything else?

This is in essence just an update of the existing listing, please. :)

**Comment by seanmarcia** [comment]
Updated. Sorry for the delay.
