### ISSUE TITLE
[New Project]: La Cuentoneta

### ISSUE THREAD

**Issue by rolivencia** [github/forgoodfirstissue#99]
### Is this project already existing in the app?

- [X] I have searched the existing projects

### Tell us about the project

La Cuentoneta is a non-for-profit and open source project that aims to create a community space for sharing short pieces of literature. This initiative was originally conceived by a group of friends residing in the city of Santa Fe, Argentina, during the last days of December 2021.

The mission of the "Cuentoneta" is to collectively build an accessible, user-friendly, and gamified platform that is useful for promoting, sharing, and enjoying digital reading. We aim to achieve this through the publication of short writings in thematic storylists, emulating the playlists used by audio platforms like Spotify and video platforms like YouTube; attempting to redefine the format of short story anthologies.

Currently we're supporting an UI in Spanish and storylists both in English and Spanish.

### Is the Project a DPG (Digital Public Good)

- [X] This Project is a DPG

### Does the project list which Sustainable Development Goals it addresses in its labels?

- [X] Yes
- [ ] No

### Code of Conduct

- [X] I've read the Code of Conduct and understand my responsibilities as a member of the GitHub community

### Anything else?

You can check the current version of the platform at https://cuentoneta.ar

**Comment by seanmarcia** [comment]
Project has been added!
